name: posts_app
description: "posts App With Clean Archetecture."


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  flutter_bloc: ^8.1.6
  equatable:
  get_it:
  internet_connection_checker:
  http:
  shared_preferences: ^2.2.3
  dartz: ^0.10.1




  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:


  uses-material-design: true

  